apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.webapp.name }}
  ports:
  - port: {{ .Values.webapp.number }}
    targetPort: {{ .Values.webapp.container.port }}
  run: {{ .Values.webapp.run }}