apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.webapp.name }}
  ports:
  - port: {{ .Values.webapp.why }}
    targetPort: {{ .Values.webapp.container.port }}
run: echo ${{ spec.ports.port }}