apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.webapp.name }}
  ports:
  - port: {{ .Values.container.subport }}
    targetPort: {{ .Values.container.port }}