apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.container.port }}
    targetPort: {{ .Values.mongo.container.port }}
