name: dev

on:
  push:
    branches:
      - dev
    paths:
      - 'dev-env/**'

env:
  ENVIRONMENT: ${{ github.ref_name }}
  GKE_SA_KEY2: ${{ secrets.GKE_SA_KEY2 }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



jobs:
  Deployment:
    uses: github/workflows/deployment.yaml@dev
    with:
      appName: "dev"

        