name: dev

on:
  push:
    branches:
      - dev
    paths:
      - 'dev-env/**'


jobs:
  Deployment:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    with:
      appName: "dev"