name: dev

on:
  push:
    branches:
      - dev
    paths:
      - 'dev-env/**'




jobs:
  Deployment:
      uses: JasonZm81/micro/.github/workflows/deployment.yaml@dev
      with:
        appName: "dev"