name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  #SonarCloud Scan
  #sonarcloud:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #    with:
  #      # Disabling shallow clone is recommended for improving relevancy of reporting
  #      fetch-depth: 0
  #  - name: SonarCloud Scan
  #    uses: sonarsource/sonarcloud-github-action@master
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #Setup Deploy to GKE      
  setup-build-publish-deploy:
    #needs: sonarcloud
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    
    steps:
    - uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: 'logical-flame-386108'
        
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    #get credentials
    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'autopilot-cluster-1'
        location: 'us-central1'

    # Get the GKE credentials so we can deploy to the cluster
    #- uses: google-github-actions/get-gke-credentials@v1
    #  with:
    #    cluster_name: ${{ env.GKE_CLUSTER }}
    #    location: ${{ env.GKE_ZONE }}
    #    credentials: ${{ secrets.GKE_SA_KEY }}
        
   # Build & Push  Docker image
    - name: QEMU Setup
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: jason81/demo-gke:l.0

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f mongo.yaml -f mongo-config.yaml -f mongo-secret.yaml -f webapp.yaml
        kubectl get services -o wide
